steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/api-main:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/api-main:$SHORT_SHA"]

options:
  logging: 'CLOUD_LOGGING_ONLY'