steps:
- name: 'login_build'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    docker build -t asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/adservice:$SHORT_SHA .
    docker build -t asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/adservice:latest .
    docker push asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/adservice:$SHORT_SHA
    docker push asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/adservice:latest

options:
  logging: 'CLOUD_LOGGING_ONLY'
