apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/junnn0021/msa-petclinic'
    path: ./Application/chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - Prod.values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic-msa

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

